#Parameter file for fastq preprocesing step
samples: "/home/max/Work/OTHER_PJS/HQ_WGS_QC/pipeline_tests/samples_manifest.tsv" #define the samples manifest file

#project name
proj_name : "QC_trimming"

############################################
#Template to pre-process fastq files
# with parameters for different tools in different rules
rules:
    trimming_pe:
        q: "20"         #quality (20, default)
        w: "4"          #window size for fastp (4, default)
        len: "15"          #minimum read length for filtering (15, default)
        cR1: "0"        #cut 5'
        cR2: "0"        #cut 5'
        tpcR1: "0"       #cut 3'
        tpcR2: "0"       #cut 3'

### - GENERAL PATHS - ###
base_out: "/home/max/Work/OTHER_PJS/HQ_WGS_QC/pipeline_tests" #modify this path to define the pipeline output folder

### - RELATIVE PATHS - ###
log_dir: "Log"                   #this path is relative to the pipeline EXECUTION FOLDER
fastqc_pre_dir: "1.FASTQC_PRE"   #this path is relative to the pipeline BASE_OUT FOLDER defined above
trim_dir: "2.TRIMMED"            #this path is relative to the pipeline BASE_OUT FOLDER defined above
fastqc_post_dir: "3.FASTQC_POST" #this path is relative to the pipeline BASE_OUT FOLDER defined above
multiqc_dir: "4.MULTI_QC"        #this path is relative to the pipeline BASE_OUT FOLDER defined above

### - PATH TOOL - ###
QC_TOOL: "fastqc"
TRIM_TOOL: "fastp"
MULTI_QC: "multiqc"

